import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import JSZip from 'jszip';

// ── Types ──────────────────────────────────────────────────────────────────

export interface HermesConfig {
  projectName: string;
  repoUrl: string;
  tools: Array<{ name: string; sourceUrl?: string }>;
  memoryProvider: 'builtin' | 'honcho' | 'hindsight' | 'mem0' | 'none';
  hasSubAgents: boolean;
  hasManifest: boolean;
  manifestPath: string;
  framework: string;
  ciProvider: 'github' | 'gitlab' | 'none';
}

// ── Template generators ────────────────────────────────────────────────────

function generateAgentManifest(config: HermesConfig): string {
  const tools = config.tools.map(t => ({
    name: t.name,
    ...(t.sourceUrl ? { source: t.sourceUrl, integrity: '# run: npx ship-safe hash <source-url> to generate' } : { local: true }),
    permissions: ['read'],
  }));

  return JSON.stringify(
    {
      $schema: 'https://shipsafecli.com/schemas/agent-manifest.v1.json',
      name: config.projectName || 'my-hermes-agent',
      version: '1.0.0',
      description: 'Hardened agent manifest generated by Ship Safe',
      tools,
      security: {
        allowlist: config.tools.map(t => t.name),
        maxRecursionDepth: config.hasSubAgents ? 2 : 1,
        requireIntegrity: true,
        memoryProvider: config.memoryProvider || 'builtin',
      },
    },
    null,
    2,
  );
}

function generateHermesPolicy(config: HermesConfig): string {
  const allowlist = config.tools.map(t => `'${t.name}'`).join(', ');
  const memoryChecks = config.memoryProvider !== 'none' ? `
    // Memory provider validation
    const MEMORY_PATTERNS = [
      /\\.hermes[\\/\\\\]memories/,
      /MEMORY\\.md$/,
      /USER\\.md$/,
      /plugins[\\/\\\\]memory[\\/\\\\]/,
    ];
    for (const file of files) {
      if (!MEMORY_PATTERNS.some(p => p.test(file))) continue;
      let content;
      try { content = fs.readFileSync(file, 'utf-8'); } catch { continue; }
      const lines = content.split('\\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (/ship-safe-ignore/i.test(line)) continue;
        if (/JSON\\.parse\\s*\\((?!.*schema|.*validate)/i.test(line)) {
          findings.push(createFinding({
            rule: 'HERMES_MEMORY_UNSAFE_DESERIALIZE',
            severity: 'high',
            title: 'Memory deserialized without schema validation',
            description: 'JSON.parse on memory data without schema validation allows poisoned memory to inject arbitrary values.',
            file,
            line: i + 1,
            matched: line.trim().slice(0, 120),
            category: 'llm',
            remediation: 'Validate memory structure with a schema (e.g. zod, ajv) before using deserialized data.',
            confidence: 'medium',
          }));
        }
      }
    }` : '';

  return `/**
 * hermes-policy.js — Ship Safe Hermes Security Policy
 * Auto-generated by: npx ship-safe init --hermes
 * Project: ${config.projectName}
 * Generated: ${new Date().toISOString().split('T')[0]}
 *
 * This plugin enforces:
 *   - Tool allowlist (only ${config.tools.length} registered tool${config.tools.length !== 1 ? 's' : ''} permitted)
 *   - Function-call injection detection
 *   - Memory layer validation (if applicable)
 *   - Sub-agent trust boundary checks
 *
 * Place this file in .ship-safe/agents/ and it runs automatically
 * on every \`ship-safe audit\` or \`ship-safe watch --deep\`.
 */

import fs from 'fs';

let BaseAgent, createFinding;
try {
  ({ BaseAgent, createFinding } = await import('ship-safe'));
} catch {
  ({ BaseAgent, createFinding } = await import('../agents/base-agent.js'));
}

// ── Allowlist ─────────────────────────────────────────────────────────────
// Only tools explicitly registered in your Hermes tool registry.
// Add/remove names here when your registry changes.
const ALLOWED_TOOLS = [${allowlist}];

// Patterns that indicate a tool name comes from LLM output (unsafe)
const DYNAMIC_TOOL_PATTERNS = [
  /toolName\\s*=\\s*(?:response|llmOutput|message|completion|result)[\\.\\[]/i,
  /dispatch\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
  /execute\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
  /invoke\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
  /call\\(\\s*(?:response|llmOutput|completion)[\\.\\[]/i,
];

export default class HermesPolicy extends BaseAgent {
  constructor() {
    super();
    this.name     = 'HermesPolicy';
    this.category = 'llm';
  }

  async analyze({ files = [] }) {
    const findings = [];
    const toolFiles = files.filter(f => /\\.(js|ts|jsx|tsx)$/.test(f));

    for (const file of toolFiles) {
      let content;
      try { content = fs.readFileSync(file, 'utf-8'); } catch { continue; }
      const lines = content.split('\\n');

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (/ship-safe-ignore/i.test(line)) continue;

        // Check for dynamic tool dispatch (function-call injection)
        if (DYNAMIC_TOOL_PATTERNS.some(p => p.test(line))) {
          findings.push(createFinding({
            rule:        'HERMES_FUNCTION_CALL_NO_ALLOWLIST',
            severity:    'critical',
            title:       'Tool dispatched from LLM output without allowlist check',
            description: 'Tool name sourced directly from LLM response — a malicious prompt could hijack execution to any registered tool.',
            file,
            line:        i + 1,
            matched:     line.trim().slice(0, 120),
            category:    'llm',
            remediation: \`Validate tool name against ALLOWED_TOOLS before dispatch:\\n  if (!ALLOWED_TOOLS.includes(toolName)) throw new Error('Unknown tool: ' + toolName);\`,
            confidence:  'high',
          }));
        }

        // Check that ALLOWED_TOOLS is actually referenced in executor files
        if (/dispatch|execute|invoke|callTool/i.test(line) && !ALLOWED_TOOLS.some(t => line.includes(t))) {
          // Low-confidence signal — only flag if file looks like a dispatcher
          if (/executor|dispatcher|runner|agent/i.test(file) && !line.includes('ALLOWED_TOOLS')) {
            findings.push(createFinding({
              rule:        'HERMES_ALLOWLIST_NOT_ENFORCED',
              severity:    'high',
              title:       'Tool dispatch found without allowlist reference',
              description: 'Executor file dispatches tools but does not reference ALLOWED_TOOLS — allowlist may not be enforced at runtime.',
              file,
              line:        i + 1,
              matched:     line.trim().slice(0, 120),
              category:    'llm',
              remediation: 'Import and check ALLOWED_TOOLS before every tool invocation.',
              confidence:  'low',
            }));
          }
        }
      }
    }
${memoryChecks}
    return findings;
  }
}
`;
}

function generateGitHubWorkflow(config: HermesConfig): string {
  return `name: Ship Safe — Hermes Security Audit

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master]

jobs:
  hermes-audit:
    name: Hermes Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Run Ship Safe — Hermes Audit
        id: audit
        run: |
          npx ship-safe audit . --hermes-only --fail-below baseline --json > audit-result.json || true
          echo "score=$(cat audit-result.json | jq -r '.score // 0')" >> $GITHUB_OUTPUT
          echo "findings=$(cat audit-result.json | jq -r '.findings | length // 0')" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const score = '\${{ steps.audit.outputs.score }}';
            const findings = '\${{ steps.audit.outputs.findings }}';
            const grade = score >= 90 ? 'A' : score >= 80 ? 'B' : score >= 70 ? 'C' : score >= 60 ? 'D' : 'F';
            const emoji = score >= 80 ? '✅' : score >= 60 ? '⚠️' : '❌';
            const body = [
              '## ' + emoji + ' Ship Safe — Hermes Security Report',
              '',
              '| Score | Grade | Findings |',
              '|-------|-------|----------|',
              \`| \${score}/100 | \${grade} | \${findings} |\`,
              '',
              score < 70
                ? '> ⚠️ Score below baseline. Run \`npx ship-safe audit . --agentic 3\` locally to auto-fix findings.'
                : '> Security posture looks good on this PR.',
              '',
              '_Powered by [Ship Safe](https://shipsafecli.com) · [Hermes Agent Security](https://shipsafecli.com/blog/hermes-agent-security-tool-registry-poisoning-function-call-injection)_',
            ].join('\\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });

      - name: Fail if score dropped below baseline
        run: npx ship-safe audit . --hermes-only --fail-below baseline
`;
}

function generateGitLabCI(config: HermesConfig): string {
  return `# Ship Safe — Hermes Security Audit
# Place this in .gitlab-ci.yml (or include it from there)

hermes-security-audit:
  stage: test
  image: node:20-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npx ship-safe audit . --hermes-only --fail-below baseline
  allow_failure: false
  artifacts:
    when: always
    reports:
      junit: ship-safe-report.xml
`;
}

function generateBaseline(config: HermesConfig): string {
  return JSON.stringify(
    {
      score: 0,
      date: new Date().toISOString().split('T')[0],
      findings: 0,
      note: 'Run `npx ship-safe audit .` to populate this baseline. CI will compare against it.',
      tools: config.tools.map(t => t.name),
      memoryProvider: config.memoryProvider,
      hasSubAgents: config.hasSubAgents,
    },
    null,
    2,
  );
}

function generateSetupGuide(config: HermesConfig): string {
  const toolList = config.tools.map(t => `- \`${t.name}\`${t.sourceUrl ? ` — ${t.sourceUrl}` : ' (local)'}`).join('\n');
  const memNote = config.memoryProvider === 'none'
    ? '- None configured'
    : config.memoryProvider === 'builtin'
    ? '- Built-in (MEMORY.md / USER.md)'
    : `- External: ${config.memoryProvider}`;

  return `# Ship Safe × Hermes Agent — Security Setup

Generated on ${new Date().toISOString().split('T')[0]} for **${config.projectName}**.

## What was generated

| File | Purpose |
|------|---------|
| \`${config.manifestPath || 'agent-manifest.json'}\` | Hardened manifest with tool allowlist + integrity fields |
| \`.ship-safe/agents/hermes-policy.js\` | Custom security agent — enforces your allowlist on every scan |
| \`.ship-safe/hermes-baseline.json\` | Baseline score — CI fails if score drops below this |
${config.ciProvider === 'github' ? '| `.github/workflows/ship-safe-hermes.yml` | CI workflow — runs on every PR |' : ''}
${config.ciProvider === 'gitlab' ? '| `.gitlab-ci.yml` (append) | CI job — runs on every MR |' : ''}

## Your registered tools (${config.tools.length})

${toolList}

## Memory provider

${memNote}

## Next steps

### 1. Add integrity hashes to your manifest

For each remote tool in \`${config.manifestPath || 'agent-manifest.json'}\`:

\`\`\`bash
npx ship-safe hash <source-url>
\`\`\`

Replace the placeholder comment with the output hash.

### 2. Run your first audit

\`\`\`bash
npx ship-safe audit .
\`\`\`

This populates \`.ship-safe/hermes-baseline.json\` with your actual score.
CI will enforce this baseline on future PRs.

### 3. Fix any findings

\`\`\`bash
# Auto-fix with the agentic loop:
npx ship-safe audit . --agentic 3 --agentic-target 80
\`\`\`

### 4. Commit everything

\`\`\`bash
git add agent-manifest.json .ship-safe/ ${config.ciProvider === 'github' ? '.github/workflows/ship-safe-hermes.yml' : ''}
git commit -m "security: add Ship Safe Hermes security configuration"
git push
\`\`\`

## Ongoing

- Run \`npx ship-safe audit .\` after adding new tools to your registry
- Re-run \`npx ship-safe init --hermes\` to regenerate this config after major changes
- The CI workflow will post a security score comment on every PR

---

_Generated by [Ship Safe](https://shipsafecli.com) v9.0.0 · [Hermes Agent Security Guide](https://shipsafecli.com/blog/hermes-agent-security-tool-registry-poisoning-function-call-injection)_
`;
}

// ── Route handler ──────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let config: HermesConfig;
  try {
    config = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  // Validate
  if (!config.tools || !Array.isArray(config.tools) || config.tools.length === 0) {
    return NextResponse.json({ error: 'At least one tool is required' }, { status: 400 });
  }
  if (config.tools.length > 50) {
    return NextResponse.json({ error: 'Too many tools (max 50)' }, { status: 400 });
  }

  // Sanitize tool names — only allow safe identifiers
  config.tools = config.tools.map(t => ({
    name: t.name.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 64),
    sourceUrl: t.sourceUrl?.startsWith('https://') ? t.sourceUrl.slice(0, 512) : undefined,
  }));

  // Generate all files
  const zip = new JSZip();

  // agent-manifest.json
  const manifestPath = config.manifestPath || 'agent-manifest.json';
  zip.file(manifestPath, generateAgentManifest(config));

  // .ship-safe/agents/hermes-policy.js
  zip.file('.ship-safe/agents/hermes-policy.js', generateHermesPolicy(config));

  // .ship-safe/hermes-baseline.json
  zip.file('.ship-safe/hermes-baseline.json', generateBaseline(config));

  // CI config
  if (config.ciProvider === 'github') {
    zip.file('.github/workflows/ship-safe-hermes.yml', generateGitHubWorkflow(config));
  } else if (config.ciProvider === 'gitlab') {
    zip.file('ship-safe-hermes-ci.yml', generateGitLabCI(config));
  }

  // Setup guide
  zip.file('SHIP_SAFE_SETUP.md', generateSetupGuide(config));

  const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

  const projectSlug = (config.projectName || 'hermes-project')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);

  return new NextResponse(zipBuffer as unknown as BodyInit, {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="ship-safe-hermes-${projectSlug}.zip"`,
      'Content-Length': String(zipBuffer.length),
    },
  });
}
